openapi: 3.0.0
info:
  title: wasaText
  version: 1.0.0
  description: API per il progetto wasaText

paths:
  /user: 
    # GET method to get the list of all users
    get:
      operationId: getListOfUser
      summary: ritorna la lista di tutti gli utenti 
      description: |
        ritorna la lista degli utenti presenti nel sistema 
      responses:
        '200':
          description: lista degli utenti 
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    # POST method to add user to the list 
    post:
      operationId: createUser
      summary: crea un nuovo utente 
      description: |
        crea un nuovo utente e restituisce il suo id 
      requestBody:
        required: true 
        content:
          application/json: 
            schema:
              type: object
              properties:
                username: 
                  type: string
                  example: marta
              required:
              - username
      responses:
        '201':
          description: utente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        # codici di errore da implementare (non me li ricordo)

  /user/{userID}:
    get: 
      operationId: getParticularUser
      description: get a single user by the id 
      summary: getuser 






components:
  schemas: 
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "marta"
  parameters:
    userid:
      name: userId
      in: path 
      required: true
      schema: 
        type: integer
      description: l'identificazione univoca dell'utente 
